#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
git clone -b v1.5.1 https://github.com/trojan-gfw/trojan.git . 2> /dev/null
cd tests/LinuxSmokeTest
./basic.sh /usr/bin/trojan
./fake-client.sh /usr/bin/trojan
